# Generated by Django 5.1.2 on 2024-11-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_pp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patent",
            name="abstract",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patent",
            name="application_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patent",
            name="assignee",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="patent",
            name="classifications",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patent",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patent",
            name="grant_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patent",
            name="inventors",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patent",
            name="jurisdictions",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patent",
            name="priority_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patent",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
